feat: add ts typedefs
IndigoUnited/js-err-code pull request #32
Opened 2020-12-18 22:49 UTC by Gozala

Adds typedefs so that users of this library can get those out of the box. I have considered adding them via jsdoc systax as per #31, however given all the overloads used in the implementation it's impossible to type those in jsdoc syntax without additional type magic & `@ts-ignore` comments.

For this reasons and the minimal surface of this lib, I think it's more practical to just have `index.d.ts` file instead.

2020-12-19 08:35 UTC, achingbrain requested changes
This needs the type checker run over the tests to ensure the types are as intended, otherwise releasing future changes will be very error prone.

This should also go out as a major to avoid breaking projects that have types, use this module and suddenly discover the types are not quite as they expected.

2020-12-19 08:35 UTC, achingbrain commented on index.d.ts
> +    reason:string|Error,
This should just be `Error`, the string detection is done in the code to encourage users to move off the v1 API but maybe now it's time to demand an `Error`.

2020-12-19 08:35 UTC, achingbrain commented on index.d.ts
> +export type Scalar = number | string | boolean | bigint | null | undefined;
Do we really want to support all of these `code` types?  I would have though it'd just be `number | string`

We do null-guard on `code` in the implementation but maybe that's unnecessary.

2020-12-19 08:35 UTC, achingbrain commented on index.d.ts
> +}
I think this is missing the `errCode(err, ext)` signature, see [Usage](https://github.com/IndigoUnited/js-err-code#usage) in the readme.

2021-01-19 13:02 UTC, hugomrdias commented
@Gozala ping

2021-01-20 04:56 UTC, Gozala commented on index.d.ts
> +    reason:string|Error,
```suggestion
    reason:Error,
```

2021-01-20 05:56 UTC, Gozala commented
Addressed review comments & is ready for another pass

2021-01-23 08:10 UTC, achingbrain approved these changes
LGTM, thanks!

2021-01-23 08:10 UTC, achingbrain commented on index.d.ts
> +  <Ext extends Object> (error:Error, ext:Ext):Err<undefined> & Ext
Consistent spacing, should be picked up by a linter really.

```suggestion
  <Ext extends Object> (error:Error, ext:Ext): Err<undefined> & Ext
```

2021-01-23 08:42 UTC, hugomrdias commented on .github/workflows/typecheck.yml
> +        node-version: [13.x]
why 13 ?

2021-01-26 18:24 UTC, Gozala commented on .github/workflows/typecheck.yml
> +        node-version: [13.x]
```suggestion
        node-version: [14.x]
```

2021-02-02 12:28 UTC, merged

2021-04-22 03:04 UTC, zorji commented
I'll need to deprecated the types in @types/err-code
https://github.com/IndigoUnited/js-err-code/pull/21

2021-04-22 03:18 UTC, zorji commented
PR created https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52518